name: Check Plate Availability

on:
  schedule:
    - cron: "32 14 * * *" # Run at 00:00 every day (midnight) 

jobs:
  check_plate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run your script
        run: |
          python plate_checker.py